name: doppio_dev_ixn
description: iXn

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 7.0.0-nullsafety.5

  # for mutable state
  equatable: #1.1.1
    git:
      url: https://github.com/Gorniv/equatable
      ref: master

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.2
  url_launcher: 6.0.2
  url_launcher_macos: 2.0.0
  url_launcher_web: 2.0.0
  semaphore: 0.1.4

  hive: 2.0.0

  uuid: 3.0.1
  rxdart: 0.26.0
  bot_toast: 4.0.0+1
  file_selector: 0.8.0
  file_selector_web: 0.8.0

  # file_access:
  #   git: https://github.com/Gorniv/file_access

  # file_manager:
  #   git: 
  #     url: https://github.com/rodydavis/file_manager
  #     ref: master
  #     path: file_manager

  archive: 3.1.2
  line_awesome_icons: 1.0.4+2

dependency_overrides:
  http: 0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  pedantic: 1.11.0
  doppio_utils_config:
    git:
      url: https://github.com/doppio-dev/utils
      ref: v0.0.4
      path: config
  dwds: 8.0.3
  hive_generator: 1.0.0
    

  translator: #0.1.4
    git:
      url: https://github.com/Gorniv/google-translator
    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  main_locale: en_US
