# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do
    # get_provisioning_profile   # invokes sigh

    build_mac_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner",
      output_directory: "../release/macos", # Destination directory. Defaults to current directory.
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      # export_options: {
      #   method: "app-store",
      #   provisioningProfiles: { 
      #     "dev.doppio.ixn" => "iXn(CL6F555UXF.dev.doppio.ixn)- Mac App Store",
      #   }
      # }
    )
    # notarize(
    #   package: "../release/macos", # Path to package to notarize, e.g. .app bundle or disk image
    #   bundle_id: "dev.doppio.ixn" #CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    # )
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
