# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :rel_mac do
    # get_provisioning_profile()   # invokes sigh

    build_mac_app(
      destination: "generic/platform=macOS",
      workspace: "Runner.xcworkspace", 
      scheme: "Runner",
      output_directory: "../release/macos", # Destination directory. Defaults to current directory.
      export_team_id: "CL6F555UXF",
      export_method: "app-store",
      # installer_cert_name: "3rd Party Mac Developer Installer: Igor Kravchenko (CL6F555UXF)",
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "dev.doppio.ixn" => "iXn(CL6F555UXF.dev.doppio.ixn)- Mac App Store",
        }
      }
    )
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

  desc "Release from source code on local machine"
  lane :local do
    build_mac_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner",
      output_directory: "../release/macos", # Destination directory. Defaults to current directory.
      export_team_id: "CL6F555UXF",
      export_method: "app-store",
    )
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
