import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedProjectSetting {
  final List<ProjectSettingModel> results;

  AutogeneratedProjectSetting({this.results});

  factory AutogeneratedProjectSetting.fromJson(Map<String, dynamic> json) {
    List<ProjectSettingModel> temp;
    if (json['results'] != null) {
      temp = <ProjectSettingModel>[];
      json['results'].forEach((v) {
        temp.add(ProjectSettingModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedProjectSetting(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ProjectSettingModel extends Equatable {
  final int id;
  final String name;

  ProjectSettingModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ProjectSettingModel.fromJson(Map<String, dynamic> json) {
    return ProjectSettingModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}
